title: Bawo!
description: > # this means to ignore newlines until "baseurl:"
  Personal blog and portfolio
permalink: ':title/'
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://alexfdz.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: _alexfdz

# Author Settings
author: Alex Fernandez # add your name
author-img: me.jpeg # add your photo
about-author: I am a web developer focusing on front-end development. Always hungry to keep learning. # add description
social-twitter: _alexfdz
social-github: alexfdz
social-linkedin: alexfdz
social-email: alexfdz@gmail.com

# Disqus
discus-identifier: # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
